#!/usr/bin/env bash
JUPYTER_LAB_PORT="${1:-10006}"

DOCKER_TAG="rethinking-jupyter-lab"
docker build --tag "$DOCKER_TAG" .

WORKDIR="/home/$USER/work"
docker run --rm \
    -p "$JUPYTER_LAB_PORT":"$JUPYTER_LAB_PORT" \
    --env JUPYTER_ENABLE_LAB=yes \
    --env NB_USER="$USER" \
    --mount type=bind,src=${HOME},dst=${HOME} \
    --workdir $HOME \
    --user root \
    "$DOCKER_TAG" \
    start.sh jupyter lab \
    --port "$JUPYTER_LAB_PORT" \
    --notebook-dir=$(pwd) \
    --NotebookApp.password='sha1:5970cc8206fe:82124bd5879c43de97768e910e3e13d2534d5a63'
